### ISSUE TITLE
[Bug] url not valid

### ISSUE THREAD

**Issue by ghost** [MerlynAllen/jlu-vpns-warp#1]

**Comment by MerlynAllen** [comment]
食用方式：传送门URL的后面拼接一个"?"+**完整**URL
如：`https://webvpn.jlu.edu.cn/https/77726476706e69737468656265737421fdf253903e3e695c720d87e29f5c373d3f27c82a2a/jlu-vpns-dokodemo-door/?https://www.baidu.com`是一个跳转到百度的URL。
`https://webvpn.jlu.edu.cn/https/77726476706e69737468656265737421fdf253903e3e695c720d87e29f5c373d3f27c82a2a/jlu-vpns-dokodemo-door/`是传送门入口，`?`url传参，'https://www.baidu.com'是一个不缺少协议头的完整的URL。

**Comment by MerlynAllen** [comment]
其它问题的话，还是留一下你测试用的URL吧，我没有全面测试。可能正则有问题

**Comment by MerlynAllen** [comment]
抱歉，转义问题，已解决

**Comment by ghost** [comment]
thx

**Comment by ghost** [comment]
我还以为是学校层面加 whitelist 了……
